apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dns-tcp
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: dns
      port: 53
      targetPort: dns
      protocol: TCP
